//! asset-gen: single source of truth for all pet sprites.
//! Emits:
//!   firmware/src/sprites_gen.h            (RGB332 PROGMEM frames for the ESP32)
//!   pc/petd/assets/frames/*.png           (RGBA frames for the desktop pet)
//!   pc/petd/src/assets_gen.rs             (embedding tables for petd)

mod beemo;
mod canvas;
mod clawd;
mod egg;
mod overlays;
mod props;

use canvas::{rgb332, Anim, Canvas, W};
use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

pub const STATE_NAMES: [&str; 13] = [
    "idle", "coding", "thinking", "searching", "testing", "building", "debugging", "error",
    "success", "waiting", "notify", "celebrating", "sleep",
];
pub const CHAR_NAMES: [&str; 3] = ["clawd", "beemo", "egg"];

fn root() -> PathBuf {
    // pc/asset-gen -> project root
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..").canonicalize().unwrap()
}

fn pick_transparent(used: &std::collections::HashSet<u8>) -> u8 {
    for cand in [0xE3u8, 0x1F, 0x83, 0x9F, 0x63] {
        if !used.contains(&cand) {
            return cand;
        }
    }
    (0u8..=255).find(|v| !used.contains(v)).expect("no free RGB332 value")
}

fn canvas_rgba(c: &Canvas) -> Vec<u8> {
    let mut v = Vec::with_capacity((W * W * 4) as usize);
    for p in &c.px {
        match p {
            Some(rgb) => v.extend_from_slice(&[rgb[0], rgb[1], rgb[2], 255]),
            None => v.extend_from_slice(&[0, 0, 0, 0]),
        }
    }
    v
}

fn canvas_332(c: &Canvas, transparent: u8) -> Vec<u8> {
    c.px.iter()
        .map(|p| match p {
            Some(rgb) => {
                let v = rgb332(*rgb);
                assert_ne!(v, transparent, "palette color collides with transparent key");
                v
            }
            None => transparent,
        })
        .collect()
}

fn write_png(path: &Path, rgba: &[u8]) {
    let file = fs::File::create(path).unwrap_or_else(|e| panic!("create {}: {e}", path.display()));
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), W as u32, W as u32);
    enc.set_color(png::ColorType::Rgba);
    enc.set_depth(png::BitDepth::Eight);
    let mut w = enc.write_header().unwrap();
    w.write_image_data(rgba).unwrap();
}

fn main() {
    let root = root();
    let frames_dir = root.join("pc").join("petd").join("assets").join("frames");
    let fw_dir = root.join("firmware").join("src");
    fs::create_dir_all(&frames_dir).unwrap();
    fs::create_dir_all(&fw_dir).unwrap();

    let chars: Vec<Vec<Anim>> = vec![clawd::anims(), beemo::anims(), egg::anims()];
    for anims in &chars {
        assert_eq!(anims.len(), 13);
    }
    let ovl = overlays::overlays();

    // ---- collect every used RGB332 value to pick a transparent key ----
    let mut used = std::collections::HashSet::new();
    let all_canvases: Vec<&Canvas> = chars
        .iter()
        .flat_map(|a| a.iter().flat_map(|an| an.frames.iter().map(|f| &f.canvas)))
        .chain(ovl.iter().flatten())
        .collect();
    for c in &all_canvases {
        for p in c.px.iter().flatten() {
            used.insert(rgb332(*p));
        }
    }
    let transparent = pick_transparent(&used);
    println!("palette: {} distinct RGB332 colors, transparent key 0x{transparent:02X}", used.len());

    // ---- PNGs + petd embedding table ----
    let mut rs = String::from("// @generated by asset-gen — do not edit\n\n");
    rs.push_str("pub const STATE_NAMES: [&str; 13] = [\n    ");
    for s in STATE_NAMES {
        write!(rs, "\"{s}\", ").unwrap();
    }
    rs.push_str("\n];\n");
    rs.push_str("pub const CHAR_NAMES: [&str; 3] = [\"clawd\", \"beemo\", \"egg\"];\n\n");
    rs.push_str("pub struct AnimDef {\n    pub dur_ms: u16,\n    pub frames: &'static [(&'static [u8], i8)], // (png bytes, bob px)\n}\n\n");
    rs.push_str("pub static ANIMS: [[AnimDef; 13]; 3] = [\n");
    for (ci, anims) in chars.iter().enumerate() {
        rs.push_str("    [\n");
        for (si, anim) in anims.iter().enumerate() {
            write!(rs, "        AnimDef {{ dur_ms: {}, frames: &[", anim.dur_ms).unwrap();
            for (fi, f) in anim.frames.iter().enumerate() {
                let name = format!("{}_{}_{}.png", CHAR_NAMES[ci], STATE_NAMES[si], fi);
                write_png(&frames_dir.join(&name), &canvas_rgba(&f.canvas));
                write!(rs, "(include_bytes!(\"../assets/frames/{name}\"), {}), ", f.bob).unwrap();
            }
            rs.push_str("] },\n");
        }
        rs.push_str("    ],\n");
    }
    rs.push_str("];\n\n");
    rs.push_str("/// overlays[char][level-3] for char 0=clawd 1=beemo (egg has none)\n");
    rs.push_str("pub static OVERLAYS: [[&'static [u8]; 3]; 2] = [\n");
    for (ci, ovls) in ovl.iter().enumerate() {
        rs.push_str("    [");
        for (li, c) in ovls.iter().enumerate() {
            let name = format!("overlay_{}_{}.png", CHAR_NAMES[ci], li + 3);
            write_png(&frames_dir.join(&name), &canvas_rgba(c));
            write!(rs, "include_bytes!(\"../assets/frames/{name}\"), ").unwrap();
        }
        rs.push_str("],\n");
    }
    rs.push_str("];\n");
    let petd_src = root.join("pc").join("petd").join("src");
    fs::create_dir_all(&petd_src).unwrap();
    fs::write(petd_src.join("assets_gen.rs"), rs).unwrap();

    // ---- firmware header with frame dedup ----
    let mut h = String::from("// @generated by asset-gen — do not edit\n#pragma once\n#include <Arduino.h>\n#include <pgmspace.h>\n\n");
    write!(h, "#define SPR_W 40\n#define SPR_NUM_STATES 13\n#define SPR_NUM_CHARS 3\n#define SPR_TRANSPARENT 0x{transparent:02X}\n\n").unwrap();
    h.push_str("typedef struct {\n  const uint8_t* const* frames;\n  const int8_t* bob;\n  uint8_t count;\n  uint16_t dur_ms;\n} SprAnim;\n\n");

    let mut dedup: HashMap<Vec<u8>, usize> = HashMap::new();
    let mut arrays = String::new();
    let mut next_id = 0usize;
    let mut frame_id = |data: Vec<u8>, arrays: &mut String| -> usize {
        if let Some(&id) = dedup.get(&data) {
            return id;
        }
        let id = next_id;
        next_id += 1;
        write!(arrays, "static const uint8_t SPR_F{id}[{}] PROGMEM = {{\n", data.len()).unwrap();
        for chunk in data.chunks(40) {
            arrays.push_str("  ");
            for b in chunk {
                write!(arrays, "0x{b:02X},").unwrap();
            }
            arrays.push('\n');
        }
        arrays.push_str("};\n");
        dedup.insert(data, id);
        id
    };

    let mut seqs = String::new();
    let mut table = String::from("static const SprAnim SPR_ANIMS[SPR_NUM_CHARS][SPR_NUM_STATES] = {\n");
    for (ci, anims) in chars.iter().enumerate() {
        table.push_str("  {\n");
        for (si, anim) in anims.iter().enumerate() {
            let ids: Vec<usize> = anim.frames.iter().map(|f| frame_id(canvas_332(&f.canvas, transparent), &mut arrays)).collect();
            write!(seqs, "static const uint8_t* const SPR_SEQ_{ci}_{si}[] = {{").unwrap();
            for id in &ids {
                write!(seqs, "SPR_F{id},").unwrap();
            }
            seqs.push_str("};\n");
            write!(seqs, "static const int8_t SPR_BOB_{ci}_{si}[] = {{").unwrap();
            for f in &anim.frames {
                write!(seqs, "{},", f.bob).unwrap();
            }
            seqs.push_str("};\n");
            write!(table, "    {{SPR_SEQ_{ci}_{si}, SPR_BOB_{ci}_{si}, {}, {}}},\n", ids.len(), anim.dur_ms).unwrap();
        }
        table.push_str("  },\n");
    }
    table.push_str("};\n\n");

    let mut ovl_table = String::from("// overlays[char][level-3], char 0=clawd 1=beemo\nstatic const uint8_t* const SPR_OVERLAYS[2][3] = {\n");
    for ovls in ovl.iter() {
        ovl_table.push_str("  {");
        for c in ovls.iter() {
            let id = frame_id(canvas_332(c, transparent), &mut arrays);
            write!(ovl_table, "SPR_F{id},").unwrap();
        }
        ovl_table.push_str("},\n");
    }
    ovl_table.push_str("};\n");

    h.push_str(&arrays);
    h.push('\n');
    h.push_str(&seqs);
    h.push('\n');
    h.push_str(&table);
    h.push_str(&ovl_table);
    fs::write(fw_dir.join("sprites_gen.h"), &h).unwrap();

    println!(
        "wrote {} unique frames ({} KB flash), header + {} PNGs",
        next_id,
        next_id * 1600 / 1024,
        chars.iter().map(|a| a.iter().map(|an| an.frames.len()).sum::<usize>()).sum::<usize>() + 6
    );

    write_preview(&root, &chars, &ovl);
}

/// Contact sheet for visual review: rows = clawd/beemo/egg states (frame 0),
/// then frame 1 rows, then overlay composites on idle.
fn write_preview(root: &Path, chars: &[Vec<Anim>], ovl: &[[Canvas; 3]; 2]) {
    const SCALE: usize = 4;
    const CELL: usize = 40 * SCALE + 8;
    let cols = 13usize;
    let mut rows: Vec<Vec<Canvas>> = Vec::new();
    for (ci, anims) in chars.iter().enumerate() {
        for fi in 0..2 {
            rows.push(anims.iter().map(|a| a.frames[fi.min(a.frames.len() - 1)].canvas.clone()).collect());
        }
        if ci < 2 {
            let idle = &anims[0].frames[0].canvas;
            let mut row = Vec::new();
            for o in &ovl[ci] {
                let mut c = idle.clone();
                c.blit(o);
                row.push(c);
            }
            rows.push(row);
        }
    }
    let (pw, ph) = (cols * CELL, rows.len() * CELL);
    let mut img = vec![40u8; pw * ph * 4]; // dark gray bg
    for i in 0..pw * ph {
        img[i * 4 + 3] = 255;
    }
    for (ry, row) in rows.iter().enumerate() {
        for (cx, canvas) in row.iter().enumerate() {
            for y in 0..40usize {
                for x in 0..40usize {
                    if let Some(rgb) = canvas.px[y * 40 + x] {
                        for sy in 0..SCALE {
                            for sx in 0..SCALE {
                                let px = cx * CELL + 4 + x * SCALE + sx;
                                let py = ry * CELL + 4 + y * SCALE + sy;
                                let idx = (py * pw + px) * 4;
                                img[idx] = rgb[0];
                                img[idx + 1] = rgb[1];
                                img[idx + 2] = rgb[2];
                            }
                        }
                    }
                }
            }
        }
    }
    let path = root.join("preview.png");
    let file = fs::File::create(&path).unwrap();
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), pw as u32, ph as u32);
    enc.set_color(png::ColorType::Rgba);
    enc.set_depth(png::BitDepth::Eight);
    enc.write_header().unwrap().write_image_data(&img).unwrap();
    println!("preview: {}", path.display());
}
